run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec