# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: local
    hooks:
    -   id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        args: ['-w']
        files: '\.go$'

    -   id: go-imports
        name: go imports
        entry: goimports
        language: system
        args: ['-w']
        files: '\.go$'

    -   id: go-mod-tidy
        name: go mod tidy
        entry: go
        language: system
        args: ['mod', 'tidy']
        files: 'go\.(mod|sum)$'
        pass_filenames: false

    -   id: go-test
        name: go test
        entry: go
        language: system
        args: ['test', '-race', '-coverprofile=coverage.out', './...']
        files: '\.go$'
        pass_filenames: false

    -   id: go-lint
        name: golangci-lint
        entry: golangci-lint
        language: system
        args: ['run', '--fix']
        files: '\.go$'
        pass_filenames: false

    -   id: go-build
        name: go build
        entry: go
        language: system
        args: ['build', '-o', 'build/genkit-migrate', './cmd/genkit-migrate']
        files: '\.go$'
        pass_filenames: false

    -   id: go-reportcard-check
        name: go reportcard grade check
        entry: ./scripts/check-reportcard.sh
        language: system
        files: '\.go$'
        pass_filenames: false